name: Publish to NuGet
on:
  push:
    tags:
      - v*

jobs:
  publish-nuget:
  #https://github.com/Lombiq/GitHub-Actions/blob/dev/Docs/Workflows.md#nuget-publish-workflow
    #uses: EasyOC/GitHub-Actions/.github/workflows/publish-nuget.yml@version_rule
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@dev
    secrets:
      API_KEY: ${{ secrets.NUGET_API_KEY }}
