name: Release - CI
on:
  push:
    branches: [ main ]
    tags: 
      - 'v*.*.*'
jobs:
  publish-nuget:
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@dev
    secrets:
      API_KEY: ${{ secrets.NUGET_API_KEY }}
